#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(KC_UP, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_NO, KC_DOWN, MT(MOD_LCTL,KC_A), MT(MOD_LSFT,KC_S), MT(MOD_LGUI,KC_D), LT(1,KC_F), LT(3,KC_G), LT(3,KC_H), LT(2,KC_J), MT(MOD_LGUI | MOD_RGUI,KC_K), MT(MOD_LSFT | MOD_RSFT,KC_L), MT(MOD_LCTL | MOD_RCTL,KC_SCLN), KC_NO, KC_DEL, LT(3,KC_Z), KC_X, KC_C, LT(3,KC_V), LT(3,KC_B), KC_N, KC_M, KC_COMM, KC_DOT, LT(3,KC_SLSH), KC_NO, KC_ESC, KC_SPC, KC_BSPC, KC_TAB, KC_ENT),
    [1] = LAYOUT(KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGUP, KC_HOME, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_TRNS, KC_TRNS, KC_TRNS, KC_GRV, KC_QUOT, KC_ESC, KC_PGDN, KC_END, KC_EQL, KC_MINS, KC_LBRC, KC_RBRC, KC_BSLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [2] = LAYOUT(KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGUP, KC_HOME, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_GRV, KC_QUOT, KC_ESC, KC_PGDN, KC_END, KC_EQL, KC_MINS, KC_LBRC, KC_RBRC, KC_BSLS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [3] = LAYOUT(KC_NO, S(KC_1), S(KC_2), S(KC_3), S(KC_4), S(KC_5), S(KC_6), S(KC_7), S(KC_8), S(KC_9), S(KC_0), KC_TRNS, CUSTOM(7), KC_NO, KC_NO, KC_NO, KC_NO, CUSTOM(2), CUSTOM(0), CUSTOM(1), CUSTOM(2), CUSTOM(3), KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, CUSTOM(4), CUSTOM(6), KC_NO, KC_NO, CUSTOM(6), KC_NO, CUSTOM(4), CUSTOM(6), KC_TRNS, KC_NO, KC_MS_BTN2, KC_MS_BTN1, KC_MS_BTN3, KC_MS_BTN3, KC_MS_BTN1)
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed) {
        switch (keycode) {
            case QK_MACRO_0:
                SEND_STRING(SS_DOWN(X_LCTL)SS_DOWN(X_LSFT)SS_TAP(X_ENT));
                return false;
            case QK_MACRO_1:
                SEND_STRING(SS_DOWN(X_LCTL)SS_DOWN(X_LSFT)SS_TAP(X_ENT));
                return false;
            case QK_MACRO_2:
                SEND_STRING(SS_DOWN(X_LCTL)SS_DOWN(X_LSFT)SS_TAP(X_ENT));
                return false;
            case QK_MACRO_3:
                SEND_STRING(SS_DOWN(X_LCTL)SS_DOWN(X_LSFT)SS_TAP(X_ENT));
                return false;
            case QK_MACRO_4:
                SEND_STRING(SS_DOWN(X_LCTL)SS_DOWN(X_LSFT)SS_TAP(X_ENT));
                return false;
        }
    }

    return true;
};


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

